config/routes.rb
Rails.application.routes.draw do
  resources :produtos
  match 'produtos/:id/pay' => "produtos#pay_produto", via: :post, as: :pay_produto
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  require 'payments'
  before_action :set_produto, only: [:show, :edit, :update, :destroy, :pay_produto]  

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  def pay_produto
    if @produto.esta_pago
      respond_to do |format|
        format.html { redirect_to @produto, notice: 'Produto has already been paid.' }
        format.json { render :show, location: @produto }
      end
    end
    p = Pagamento.new
    p.create_default_customer_if_not_exists
    token_credit_card = params[:stripeToken]
    valor = 0
    valor = @produto.preco_unitario * @produto.quantidade
    valor *= 100
    result = p.pay_required_produto valor.to_i, token_credit_card
    logger.info "Result: #{result.inspect}"
    customer_info_map = p.get_customer_info
    if result
      @produto.update(esta_pago: true)
      PaymentMailer.with(produto: @produto, email: customer_info_map["email"])
        .send_product_paid_notification.deliver_later
      respond_to do |format|
        format.html { redirect_to @produto, notice: 'Produto has been successfully paid.' }
        format.json { render :show, location: @produto }
      end
    else
      last_error = p.get_last_error
      PaymentMailer.with(
        produto: @produto, 
        stripe_exception: "#{last_error.class}: #{last_error.message}", 
        email: customer_info_map["email"]
      ).send_product_payment_error_notification.deliver_later
      respond_to do |format|
        format.html { redirect_to @produto, notice: 'Produto cannot be paid.' }
        format.json { render :show, location: @produto }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:descricao, :preco_unitario, :quantidade)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TesteBlumpa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/produtos/_form.html.erb
<%= form_with(model: produto, local: true) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :preco_unitario %>
    <%= form.text_field :preco_unitario %>
  </div>

  <div class="field">
    <%= form.label :quantidade %>
    <%= form.number_field :quantidade %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editing Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produtos</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th>Preco unitario</th>
      <th>Quantidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.descricao %></td>
        <td><%= produto.preco_unitario %></td>
        <td><%= produto.quantidade %></td>
        <td><%= link_to 'Show', produto %></td>
        <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
        <td><%= link_to 'Destroy', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produto', new_produto_path %>

app/views/produtos/new.html.erb
<h1>New Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Back', produtos_path %>

app/views/produtos/show.html.erb
<style type="text/css">
	.pago {
		color: green;
	}
</style>
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @produto.descricao %>
</p>

<p>
  <strong>Preco unitario:</strong>
  <%= @produto.preco_unitario %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @produto.quantidade %>
</p>
<%#= link_to 'Pay', pay_produto_path(@produto), method: :post %> 
<%
valor = 0
valor = @produto.preco_unitario * @produto.quantidade if @produto.preco_unitario and @produto.quantidade
valor *= 100
#Valor passado é em centavos
%>
<table>
	<tr>
		<td>
			<%# @produto.esta_pago = false %>
			<% unless @produto.esta_pago %>
			<%= form_tag pay_produto_path(@produto), method: :post do %>
				<script
					src="https://checkout.stripe.com/checkout.js" class="stripe-button"
					data-key="pk_test_vQXTAUEzZxRqZH0JUIWtDWMo"
					data-amount="<%= valor.to_i %>"
					data-name="Demo Site"
					data-description="Example charge"
					data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
					data-locale="auto">
				</script>
			<% end %>
			<% else %>
				<b class="pago">Pago</b>
			<% end %>
		</td>
		<td>
			<%= link_to 'Edit', edit_produto_path(@produto) %>
		</td>
		<td>
			<%= link_to 'Back', produtos_path %>
		</td>
	</tr>
</table>